# comparative-demo/kubernetes/03-order-service.yaml (MODIFIED FOR LOCAL IMAGES & LOADBALANCER)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:v1   # <<<=== CHANGED: Removed username prefix
        imagePullPolicy: Never      # <<<=== ADDED: Use the locally built image only
        ports:
        - containerPort: 5003
        # IMPORTANT FOR HPA: Define resource requests so K8s knows the base CPU usage
        resources:
          requests:
            cpu: "50m" # Request 0.05 CPU core (adjust if needed)
        readinessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 5 # May need longer if downstream checks are added
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: order-service # DNS name (used only for external access here)
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 5003       # Port the Service listens on (internally AND externally for LoadBalancer)
      targetPort: 5003 # Port on the Pod to forward traffic to
  type: LoadBalancer   # <<<=== CHANGED: Use LoadBalancer for easier access on localhost:5003 (on Docker Desktop)
  # nodePort field is not used with type: LoadBalancer